-- CockroachDB/PostgreSQL portfolio tables.
-- Prefer running the full migration: node scripts/migrate.js

CREATE TABLE IF NOT EXISTS portfolios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT,
  initial_capital DECIMAL(16,2) NOT NULL,
  current_capital DECIMAL(16,2) NOT NULL,
  status VARCHAR(10) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'RESET', 'CLOSED')),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_portfolios_user_id ON portfolios (user_id);
CREATE INDEX IF NOT EXISTS idx_portfolios_status ON portfolios (status);

CREATE UNIQUE INDEX IF NOT EXISTS uq_portfolios_active_user
  ON portfolios (user_id) WHERE status = 'ACTIVE' AND user_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_portfolios_active_anon
  ON portfolios (status) WHERE status = 'ACTIVE' AND user_id IS NULL;

CREATE TABLE IF NOT EXISTS sim_trades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  portfolio_id BIGINT NOT NULL REFERENCES portfolios(id) ON DELETE CASCADE,
  symbol VARCHAR(20) NOT NULL,
  action VARCHAR(10) NOT NULL CHECK (action IN ('BUY', 'SELL')),
  qty INT NOT NULL,
  price DECIMAL(12,4) NOT NULL,
  value DECIMAL(16,4) NOT NULL,
  pnl DECIMAL(14,4),
  price_source VARCHAR(10) NOT NULL DEFAULT 'SIM' CHECK (price_source IN ('API', 'SIM', 'MANUAL')),
  executed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sim_trades_portfolio_symbol ON sim_trades (portfolio_id, symbol);
CREATE INDEX IF NOT EXISTS idx_sim_trades_portfolio_ts ON sim_trades (portfolio_id, executed_at DESC);
