-- Systematic Trading Engine CockroachDB/PostgreSQL schema.
-- The executable canonical schema is generated from backend/src/config/initDB.js.
-- Run it with: node scripts/migrate.js

CREATE TABLE IF NOT EXISTS users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(512),
  name VARCHAR(150),
  role VARCHAR(20) NOT NULL DEFAULT 'user' CHECK (role IN ('admin', 'user')),
  provider VARCHAR(20) NOT NULL DEFAULT 'local' CHECK (provider IN ('local', 'google')),
  google_id VARCHAR(255),
  picture TEXT,
  trading_mode VARCHAR(20) NOT NULL DEFAULT 'paper' CHECK (trading_mode IN ('paper', 'live')),
  is_active BOOLEAN NOT NULL DEFAULT true,
  last_login TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS portfolios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT,
  initial_capital DECIMAL(16,2) NOT NULL,
  current_capital DECIMAL(16,2) NOT NULL,
  status VARCHAR(10) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'RESET', 'CLOSED')),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_portfolios_active_user
  ON portfolios (user_id) WHERE status = 'ACTIVE' AND user_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_portfolios_active_anon
  ON portfolios (status) WHERE status = 'ACTIVE' AND user_id IS NULL;

CREATE TABLE IF NOT EXISTS sim_trades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  portfolio_id BIGINT NOT NULL REFERENCES portfolios(id) ON DELETE CASCADE,
  symbol VARCHAR(20) NOT NULL,
  action VARCHAR(10) NOT NULL CHECK (action IN ('BUY', 'SELL')),
  qty INT NOT NULL,
  price DECIMAL(12,4) NOT NULL,
  value DECIMAL(16,4) NOT NULL,
  pnl DECIMAL(14,4),
  price_source VARCHAR(10) NOT NULL DEFAULT 'SIM' CHECK (price_source IN ('API', 'SIM', 'MANUAL')),
  executed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS daily_prices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  symbol VARCHAR(20) NOT NULL,
  exchange VARCHAR(10) NOT NULL DEFAULT 'NSE' CHECK (exchange IN ('NSE', 'BSE')),
  trade_date DATE NOT NULL,
  open_price DECIMAL(12,4) NOT NULL,
  high_price DECIMAL(12,4) NOT NULL,
  low_price DECIMAL(12,4) NOT NULL,
  close_price DECIMAL(12,4) NOT NULL,
  vwap DECIMAL(12,4),
  volume BIGINT DEFAULT 0,
  delivery_qty BIGINT DEFAULT 0,
  delivery_pct DECIMAL(6,2),
  num_trades INT,
  prev_close DECIMAL(12,4),
  change_pct DECIMAL(8,4),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_daily_prices_symbol_date UNIQUE (symbol, exchange, trade_date)
);

CREATE TABLE IF NOT EXISTS instruments (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  symbol VARCHAR(20) NOT NULL,
  company_name VARCHAR(150),
  exchange VARCHAR(10) NOT NULL DEFAULT 'NSE' CHECK (exchange IN ('NSE', 'BSE')),
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_instruments_symbol_exchange UNIQUE (symbol, exchange)
);

CREATE TABLE IF NOT EXISTS password_resets (
  user_id INT NOT NULL PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  token VARCHAR(64) NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS feedback (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT,
  name VARCHAR(100),
  email VARCHAR(255),
  type VARCHAR(50) NOT NULL DEFAULT 'general',
  message TEXT NOT NULL,
  rating INT CHECK (rating IS NULL OR (rating >= 1 AND rating <= 5)),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
